# Introduction à PyTorch : Tensor

C'est le premier cours sur PyTorch avec l'utilisation de la structure de donnée utilisée par PyTorch, les tensors.

Les tensors sont de simples tableaux à n dimensions. Leur seule différence avec ces simples tableaux est que les tensors sont adaptés à tourner sur GPU ou CPU, ce qui améliore dans le cas du GPU grandement les performances du code (même plus que grandement en réalité, on gagne un temps très précieux).

Voyons alors la syntaxe :

In [1]:
import torch

tensor([1, 2, 3, 4])


In [4]:
x = torch.tensor([1, 2, 3, 4]) # 1D tensor
print(x)

x = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]]) # 2D tensor
print(x)

x = torch.tensor([ [[1, 2, 3, 4], [5, 6, 7, 8]], [[9, 10, 11, 12], [13, 14, 15, 16]] ]) # 3D tensor
print(x)

tensor([1, 2, 3, 4])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
tensor([[[1, 2, 3, 4],
         [5, 6, 7, 8]],

        [[1, 2, 3, 4],
         [5, 6, 7, 8]]])
